[package]
name = "spl-token"
version = "7.0.0"
description = "Solana Program Library Token"
authors = { workspace = true}
repository = { workspace = true}
license = { workspace = true}
edition = { workspace = true}

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.9"
bytemuck = "1.20.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-program = "2.1.0"
thiserror = "2.0"

[dev-dependencies]
lazy_static = "1.5.0"
mollusk-svm = { version = "0.0.13", git = "https://github.com/buffalojoec/mollusk.git" }
proptest = "1.5"
serial_test = "3.2.0"
solana-sdk = "2.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[package.metadata.solana]
program-id = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
